version: "3.8"

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=laravel
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
    depends_on:
      - db
    volumes:
      - ./backend:/var/www/html

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5173:5173"
    stdin_open: true
    tty: true
    restart: unless-stopped
    volumes:
      - ./frontend:/app
      - /app/node_modules

  db:
    image: postgres:15
    container_name: db
    restart: always
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
